---
# This is the top-level playbook that defines our entire infrastructure.


#- hosts: localhost
#  vars_files:
#    - group_vars/localhost
#  roles:
#    - hetzner-server


- hosts: all
  gather_facts: True

  roles:
    - role: dotfiles
      dotfiles_files: "{{ dotfiles.dotfiles_files }}"
      dotfiles_zsh_files: "{{ dotfiles.dotfiles_zsh_files }}"
      dotfiles_shellrc_files: "{{ dotfiles.dotfiles_shellrc_files }}"
      dotfiles_git_files: "{{ dotfiles.dotfiles_git_files }}"
      dotfiles_version: "91d715af51a0b64d3fec0fc142f7248447062b39"

- hosts: all
  user: deploy
  become: True
  gather_facts: True

  roles:
    - role: dotfiles
      dotfiles_files: "{{ dotfiles.dotfiles_files }}"
      dotfiles_zsh_files: "{{ dotfiles.dotfiles_zsh_files }}"
      dotfiles_shellrc_files: "{{ dotfiles.dotfiles_shellrc_files }}"
      dotfiles_git_files: "{{ dotfiles.dotfiles_git_files }}"
      dotfiles_version: "91d715af51a0b64d3fec0fc142f7248447062b39"
    - os_upgrade    # up-to-date operating system
    - role: package_install
      package_list: "{{ package_install.package_list }}"
    - ansible-role-timezone
    - common
    - role: backup
      files: "{{ backup.files }}"
    - role: ansible-role-cron
      cron_daemon: "{{ cron_daemon }}"
#    - ansible-role-docker
#    - ansible-role-certbot


