---
# This is the top-level playbook that defines our entire infrastructure.


#- hosts: localhost
#  vars_files:
#    - group_vars/localhost
#  roles:
#    - hetzner-server

- hosts: all
  user: deploy
  become: True
  gather_facts: True

  roles:
    - os_upgrade    # up-to-date operating system
    - role: package_install
      package_list: "{{ package_install.package_list }}"
    - ansible-role-timezone
    - common
    - role: dotfiles
      dotfiles_files: "{{ dotfiles.dotfiles_files }}"
    - role: backup
      files: "{{ backup.files }}"
    - role: ansible-role-cron
      cron_daemon: "{{ cron_daemon }}"
#    - ansible-role-docker
#    - ansible-role-certbot


#- hosts: local
#  user: deploy
#  become: True
#  gather_facts: True

      #  roles:
      #    - backup
