---
################################################################################
# Set your variables here.
################################################################################


# 
# role "common" settings
#
hostname: t540.home
