---

- name: Perform os_specific install tasks
  import_tasks: install_debian.yml
  when: "ansible_os_family|lower == 'debian'"

- name: Install required system packages
  package:
    name: "{{ powerdns_authoritative__system_packages }}"
    state: present

- name: Install required python modules
  pip:
    name: "{{ powerdns_authoritative__pip_packages }}"
    state: present
    executable: pip3
  environment:
    LC_CTYPE: 'en_US.UTF-8'
